name: My Workflow

on: [push]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  myjob:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Pull raw data
      run: |
        dvc pull data/raw/census.csv.dvc
    
    - name: Print raw data folder content
      run: |
        ls data/raw/
 
