name: My Workflow

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  myjob:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install requirements
      run: |
        pip install -r requirements.txt

    - name: Install dvc
      run: |
        pip install dvc
        pip install dvc[s3]

    - name: Pull raw data
      run: |
        dvc pull data/raw/census.csv.dvc

    - name: Reproduce pipe and push data
      run: |
        dvc repro -f
        dvc push

    - name: Execute testing
      run: |
        pytest tests -v

    - name: Run Flake8
      run: |
        pip install flake8
        flake8
