name: Render Deployment

on:
  push:
    branches:
      - main
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Render Deployment
        uses: sws2apps/render-deployment@v1.2.0
        with:
          serviceId: ${{ secrets.RENDER_ACCOUNT_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
