name: Render Deployment

on:
  push:
    branches: [ main ]

env:
  RENDER_ACCOUNT_ID: Domenico Vesia
  RENDER_APP_NAME: fastapi-app-dvesia
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to Render
        uses: renderinc/render-deploy-github-action@1.1.1
        with:
          render_account_id: ${{ env.RENDER_ACCOUNT_ID }}
          render_app_name: ${{ env.RENDER_APP_NAME }}
          env_vars: |
            AWS_ACCESS_KEY_ID=${{ env.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ env.AWS_SECRET_ACCESS_KEY }}
