services:
  - type: web
    name: fastapi-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      pip install dvc[s3]
      echo AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} >> .env
      echo AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} >> .env
      dvc pull artifacts/models/model.joblib.dvc
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
    autoDeploy: true
